# Below, we tell Release where to find our environment template and variables.
application_template: .release/application_template.yaml
environment_variables: .release/environment_variables.yaml

# NOTE - By default, Release accounts do not have GitOps enabled, which means
# that these files will only be used to generate the first v1 revision of your
# application-level default blueprint. When GitOps is disabed, pushing subsequent
# changes to the files above in your source control will *not* affect the default
# template, nor will it change the any running environment's personal copy of the
# default app-level template.
#
# You can enable GitOps by conacting your Release account team.
